#!/usr/bin/env bash

set -e

WORK_DIR=/usr/src

function handle_error() {
  local status=$?
  if [[ $status > 0 ]]; then
    echo "🔥 There was a problem building the binary. Operation aborted."
    exit 1
  fi
}
trap handle_error EXIT SIGINT

apt-get update -y

# get, configure and install newest imagemagick
echo "⚙️ Installing latest imagemagick..."
git clone https://github.com/ImageMagick/ImageMagick.git $WORK_DIR/imagemagick
cd $WORK_DIR/imagemagick
./configure --prefix=$WORK_DIR/imagemagick --without-gvc
make && make install

# compress the binary
echo "🗄️ Compressing build..."
rm -rf build
mkdir build
tar czf $WORK_DIR/imagemagick/build/imagemagick.tar.gz bin include lib

# copy the compressed file/tarball from the docker container into the repo
cp $WORK_DIR/imagemagick/build/imagemagick.tar.gz /buildpack/build/$1

echo "✅ All done!"
